name: Required Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]


jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Type label
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "Type: Enhancement, Type: Fix, Type: Foundational, Type: Hotfix"
      - name: Check Team label
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "Team: Elite ESP"
